version: '3'

services:
  backend:
    image: weslyg/shortify:latest
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - HOSTNAME=
  mongo:
    image: mongo
    ports:
    - 27017:27017
